site_name: YSH的学习笔记
site_url: https://yourusername.github.io/Note

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate # 集成目录

# 插件：自动为每个页面生成一个深入的目录 sidebar
plugins:
  - search

# 核心导航配置
nav:
  - 首页: index.md
  - JVM 详解: JVM/JVM.md
  - 并发编程: 并发编程/并发编程.md
  - Spring 核心: Spring/Spring.md
  - Spring Boot: SpringBoot/SpringBoot.md
  - SpringCloud: SpringCloud/SpringCloud.md
  - MySQL: MySQL/MySQL.md
  - Redis: Redis/Redis.md
  - Netty 入门: Netty/Netty.md
  - Docker 从入门到实践: Docker.md
  - Linux 常用命令: Linux.md
  - Git 原理与应用: Git/Git.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yayahonghong
    - icon: fontawesome/brands/weixin
      link: weixin://dl/chat?YSH13575035159