# 2025/09/03-18:58
site_name: YSH的学习笔记
site_url: https://yourusername.github.io/Note

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotate    # 代码注释
    - content.tabs.link        # 内容标签页
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式


plugins:
  - search

markdown_extensions:
  - pymdownx.details      # 支持折叠内容块
  - pymdownx.superfences  # 支持代码块和其他内容
  - admonition           # 支持提示框
  - toc:                 # 目录配置
      permalink: true    # 标题锚点
      toc_depth: 4      # 目录深度


nav:
  - 首页: index.md
  - Java 技术栈:
    - JVM:
      - JVM 基础: JVM/JVM-base.md
      - JVM: JVM/JVM.md
    - 并发编程: 并发编程/并发编程.md
    - Java 基础: Java.md
  - Spring 全家桶:
    - Spring 核心: 
      - Overview: Spring/index.md
      - 概述: Spring/Spring-Overview.md
      - 基于XML的Spring应用: Spring/Spring-XML.md
      - 基于注解的Spring应用: Spring/Spring-Annotation.md
      - Spring AOP: Spring/Spring-AOP.md
      - Spring Web: Spring/Spring-Web.md
      - Spring MVC: Spring/Spring-MVC.md
    - Spring Boot: SpringBoot/SpringBoot.md
    - SpringCloud 微服务:
      - Overview: SpringCloud/index.md
      - 概述: SpringCloud/SpringCloud-Overview.md
      - MyBatis-Plus: SpringCloud/SpringCloud-MyBatisPlus.md
  - 数据库技术:
    - MySQL: MySQL/MySQL.md
    - Redis: Redis/Redis.md
  - 网络与中间件:
    - Netty: Netty/Netty.md
    - Kafka: Kafka.md
    - Zookeeper: Zookeeper.md
  - 运维技术:
    - Docker: Docker.md
    - Linux: Linux.md
  - 开发工具:
    - Git: Git/Git.md
  - 随记:
    - 暂无: null.md
  - 其他:
    - 系统相关: 系统相关.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yayahonghong